config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :users
  resources :books do
    resources :likes
  end
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

end

app/models/Book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :liked_bys, through: :likes, class_name: 'User'
  has_many :likes
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/User.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :liked_books, through: :likes, class_name: 'Book'
  has_many :likes
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :books
  belongs_to :users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book added!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem adding your book. Please try again."
      redirect_to :back
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :photo)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new
    @like = Like.new
  end

  def create
    @like = Like.new(like_params)
    @like.user_id = current_user.id
    @like.save
    redirect_to :back
  end


private
  def like_params
    params.require(:like).permit(:book_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    #try to authenticate the user - if they authenticate successfully, an instance of the User model is returned
    @user = User.authenticate(params[:email], params[:password])
    #if an instance is returned and @user is not nil...
    if @user
    #let the user know they've been logged in with a flash message
      flash[:notice] = "You've been logged in."
      #THIS IS THE MOST IMPORTANT PART. Actually log the user in by storing their ID in the session hash with the [:user_id] key!
      session[:user_id] = @user.id
      #then redirect them to the homepage
      redirect_to "/"
    else
      #whoops, either the user wasn't in the database or their password is incorrect, so let them know, then redirect them back to the log in page
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end
  def show
    @user = User.find(params[:id])
  end




private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/new.html.erb
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 well">
    <div class="page-header">
      <h1>Add book</h1>
    </div>
    <%=form_for(Book.new, html: {class: "form-group"}) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :author %>
      <%= f.text_field :author, class: "form-control"  %>
      <%= f.label :photo %>
      <%= f.file_field :photo, class: "form-control" %>
      <br>
      <%= f.submit "Add book", class: "btn btn-danger"  %>
    <% end %>
  </div>
  <div class="col-sm-3"></div>
</div>

app/views/books/show.html.erb
<h2>Library of <%= @book.user.email %></h2>
<h3><%= @book.name %></h3>
<h6><%= @book.author %></h6>
<img src="<%= @book.photo %>" alt="bookcover" />
Likes:<%= @book.likes.count %>


<%=form_for([@book, Like.new]) do |f| %>
  <%=f.hidden_field :book_id, :value => @book.id %>
  <%=f.submit "Like", class: "btn btn-success"  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>graf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
         <a class="navbar-brand" href="/">graf</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if session[:user_id] == nil %>
            <li><%= link_to 'Log in', log_in_path %></li>
            <li><%= link_to 'Register', new_user_path %></li>
          <% else %>
            <li><%= link_to 'Log out', log_out_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><a><%= image_tag current_user.avatar.url(:thumb), class: "navatar" %></a></li>
            <li><a href='/users/<%= current_user.id %>'><%= current_user.email %></a></li>
          <% end%>
        </ul>
      </div>
    </div>
  </nav>
<div class="container">
<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>
</div>
</body>
</html>

app/views/users/index.html.erb
<%= link_to 'Add book', new_book_path %>

<% @users.each do |user| %>
  <a href='/users/<%= user.id %>'><div class="well">
    <% if user.avatar_file_name %>
      <img src="<%= user.avatar %>" alt="avatar" class="avatar" />
    <% end %>
    <span id='email'><%= user.email %></span>
  </div></a>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 well">
    <div class="page-header">
      <h1>Sign Up</h1>
    </div>
    <%=form_for(User.new, html: {class: "form-group"}) do |f| %>
      <%=f.label :email %>
      <%=f.text_field :email, class: "form-control" %>
      <%=f.label :password %>
      <%=f.password_field :password, class: "form-control"  %>
      <%=f.label :password_confirmation %>
      <%=f.password_field :password_confirmation, class: "form-control"  %>
      <%=f.label :avatar %>
      <%= f.file_field :avatar, class: "form-control" %>
      <br>
      <%=f.submit "Sign Up", class: "btn btn-danger"  %>
    <% end %>
  </div>

  <div class="col-sm-3"></div>
</div>

app/views/users/show.html.erb
<h2>Library of <%= @user.email %><img src="<%= @user.avatar %>" alt="" class="navatar"/></h2>
<ul>
  <% @user.books.each do |book| %>
  <li><h6><%= book.name %></h6>
  <%= book.author %>
  <br>
  <a href="/books/<%= book.id %>"><img src="<%= book.photo %>" alt="bookcover" /></a></li>
  <% end %>
</ul>